name: Update cf.txt with cf_clearance

on:
  workflow_dispatch: 
  push:
    branches:
      - main  # 或者你選擇的主分支

jobs:
  update-cf-clearance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Run Puppeteer script to get cf_clearance
      run: |
        xvfb-run --auto-servernum -- node src/get-cf-clearance.js

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add data/cf.json
        git commit -m "Update cf_clearance in cf.txt"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
